apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: ocs-metrics-exporter
    app.kubernetes.io/name: ocs-metrics-exporter
    app.kubernetes.io/version: 0.0.1
  name: ocs-metrics-exporter
  namespace: openshift-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: ocs-metrics-exporter
      app.kubernetes.io/name: ocs-metrics-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/component: ocs-metrics-exporter
        app.kubernetes.io/name: ocs-metrics-exporter
        app.kubernetes.io/version: 0.0.1
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - resources:
          limits:
            cpu: 150m
            memory: 150Mi
          requests:
            cpu: 50m
            memory: 50Mi
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
        image: quay.io/ocs-dev/ocs-operator
        name: ocs-metrics-exporter
        ports:
        - containerPort: 8080
        - containerPort: 8081
        command:
        - /usr/local/bin/metrics-exporter
        args:
          - --namespaces=openshift-storage
        securityContext:
          capabilities:
            drop:
              - ALL
          runAsUser: 65532
          runAsGroup: 65532
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: ceph-config
          mountPath: /etc/ceph
      serviceAccountName: ocs-metrics-exporter
      volumes:
      - name: ceph-config
        configMap:
          name: ocs-metrics-exporter-ceph-conf

