apiVersion: v1
data: {}
kind: Secret
metadata:
  name: ocs-metrics-exporter-kube-rbac-proxy-config
  namespace: openshift-storage
stringData:
  config.yaml: |-
    "authorization":
      "static":
      - "path": "/metrics"
        "resourceRequest": false
        "user":
          "name": "system:serviceaccount:openshift-monitoring:prometheus-k8s"
        "verb": "get"
      - "path": "/metrics/rbd-mirror"
        "resourceRequest": false
        "user":
          "name": "system:serviceaccount:openshift-monitoring:prometheus-k8s"
        "verb": "get"
type: Opaque
