apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: prometheus-ocs-rules
  namespace: openshift-storage
spec:
  groups:
  - name: ocs_telemetry.rules
    rules:
    - expr: "sum(\n  max(\n    (\n      kube_pod_container_resource_requests_cpu_cores{namespace=\"openshift-storage\",
        pod =~\"(noobaa-core.*|noobaa-db.*|rook-ceph-(mon|osd|mgr|mds|rgw).*)\"} *
        0 +1 \n    ) * on(node) group_left() node:node_num_cpu:sum\n  ) by (node)\n)\n"
      record: ocs:node_num_cpu:sum
    - expr: |
        sum(
          rate(
            container_cpu_usage_seconds_total{namespace="openshift-storage",container="",pod =~"(noobaa-core.*|noobaa-db.*|rook-ceph-(mon|osd|mgr|mds|rgw).*)"} [5m]
          )
        )
      record: ocs:container_cpu_usage:sum
  - name: external-cluster-services-alert.rules
    rules:
    - alert: ClusterObjectStoreState
      annotations:
        description: Cluster Object Store is in unhealthy state for more than 15s.
          Please check Ceph cluster health or RGW connection.
        message: Cluster Object Store is in unhealthy state. Please check Ceph cluster
          health or RGW connection.
        severity_level: error
        storage_type: RGW
      expr: |
        ocs_rgw_health_status{job="ocs-metrics-exporter"} > 1
      for: 15s
      labels:
        severity: critical
