apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ocs-metrics-exporter
  namespace: openshift-storage
  labels:
    app.kubernetes.io/component: ocs-metrics-exporter
    app.kubernetes.io/name: ocs-metrics-exporter
    app.kubernetes.io/version: 0.0.1
spec:
  namespaceSelector:
    matchNames:
      - openshift-storage
  selector:
    matchLabels:
      app.kubernetes.io/component: ocs-metrics-exporter
      app.kubernetes.io/name: ocs-metrics-exporter
  endpoints:
  - bearerTokenFile: "/var/run/secrets/kubernetes.io/serviceaccount/token"
    interval: 1m
    port: https-main
    path: /metrics
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      insecureSkipVerify: false
      serverName: ocs-metrics-exporter.openshift-storage.svc
  - bearerTokenFile: "/var/run/secrets/kubernetes.io/serviceaccount/token"
    interval: 1m
    port: https-main
    path: /metrics/rbd-mirror
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      insecureSkipVerify: false
      serverName: ocs-metrics-exporter.openshift-storage.svc
  - bearerTokenFile: "/var/run/secrets/kubernetes.io/serviceaccount/token"
    interval: 1m
    port: https-self
    path: /metrics
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      insecureSkipVerify: false
      serverName: ocs-metrics-exporter.openshift-storage.svc
