# permissions for end users to view storageconsumers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storageconsumer-viewer-role
rules:
- apiGroups:
  - ocs.openshift.io
  resources:
  - storageconsumers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ocs.openshift.io
  resources:
  - storageconsumers/status
  verbs:
  - get
