apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  namespace: openshift-storage
  name: example-storagecluster
spec:
  # network specifies NetworkAttachmentDefinition objects for multus network
  # a NetworkAttachmentDefinition object should exist in the namespace before 
  # it is referenced bellow
  # more info on network can be found at docs/multus.md
  # network:
  #   provider: multus
  #   selectors:
      # The selector keys are required to be `public` and `cluster`.
      # Based on the configuration, the operator will do the following:
      #   1. if only the `public` selector key is specified both public_network and cluster_network Ceph settings will listen on that interface
      #   2. if both `public` and `cluster` selector keys are specified the first one will point to 'public_network' flag and the second one to 'cluster_network'
      #
      # In order to work, each selector value must match a NetworkAttachmentDefinition object in Multus
      #
  #     public: ocs-public --> NetworkAttachmentDefinition object name in Multus
  #     cluster: ocs-cluster --> NetworkAttachmentDefinition object name in Multus
  manageNodes: false
  monPVCTemplate:
    spec:
      storageClassName: gp2
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  storageDeviceSets:
  - name: example-deviceset
    count: 3
    resources: {}
    placement: {}
    dataPVCTemplate:
      spec:
        storageClassName: gp2
        accessModes:
        - ReadWriteOnce
        volumeMode: Block
        resources:
          requests:
            storage: 1Ti
    portable: true

